### ISSUE TITLE
Let's change the GUI framework for the app from pyglet to something more universal framework.

### ISSUE THREAD

**Issue by ravigupta-design** [ravigupta-art/BollyDumb#10]

**Comment by ravigupta-design** [comment]
@shubhragupta-code  Let us work on the GUI for this one first. This would also solve the issue #15 
 PysimpleGUI seems to be good option. I implemented GUI on 'ravigupta-art/IgnouPercentageCalculator' using PysimpleGUI and it worked for 32bit OS's as well.

**Comment by ravigupta-design** [comment]
I you can learn integrating electron with flask/django or basically work with python along with electron to build the app, it will be a bonus.

**Comment by shubhragupta-code** [comment]
With flask as a framework, this issue has been solved with #19. Thus, I am closing this issue.
