### ISSUE TITLE
Need to implement timer and a timer limit.

### ISSUE THREAD

**Issue by shubhragupta-code** [ravigupta-art/BollyDumb#11]
We need to have a timer and a timer limit for user to guess a movie name. Default timer limits can be something like 2, 5 or 10 minutes.

Do we need to put a custom timer?

**Comment by triplrrr** [comment]
I believe I got a solution at https://github.com/triplrrr/BollyDumb, but I haven't tested it, since I'm not at my host machine right now. 

Edit: Need to add an end condition.

**Comment by triplrrr** [comment]
added end condition

**Comment by triplrrr** [comment]
submitted pull request

**Comment by triplrrr** [comment]
code is at https://github.com/triplrrr/BollyDumb/tree/triplrrr-contrib

**Comment by ravigupta-design** [comment]
> 
> 
> I believe I got a solution at https://github.com/triplrrr/BollyDumb, but I haven't tested it, since I'm not at my host machine right now.
> 
> Edit: Need to add an end condition.

I will look into the code soon. Thanks.

**Comment by ravigupta-design** [comment]
@triplrrr  I went through your code. Yes, it works. Thanks for the pull request, I am going to merge it soon.

**Comment by shubhragupta-code** [comment]
We are going forward with Flask instead of Pyglet and have added timer functionality.
